sudo: required
services:
  - docker

before_install:
  - docker build -t austnig94/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true austnig94/react-test npm test

after_success:
  - docker build -t austnig94/multi-client ./client
  - docker build -t austnig94/multi-nginx ./nginx
  - docker build -t austnig94/multi-server ./server
  - docker build -t austnig94/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  - docker push austnig94/multi-client
  - docker push austnig94/multi-nginx
  - docker push austnig94/multi-server
  - docker push austnig94/multi-worker

deploy:
  - provider: elasticbeanstalk
  - region: us-east-2
  - app: multi-docker
  - env: MultiDocker-env
  - bucket_name: elasticbeanstalk-us-east-2-595831816738
  - bucket_path: docker-multi
  on:
    branch: master
  access_key_id: 
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"